### ISSUE TITLE
Integrate first version of the front-end and the back-end

### ISSUE THREAD

**Issue by lorenzowind** [felipewind/client-management#15]
Hi @felipewind!

How the first version of the front-end and back-end are concluded, it's time to integrate both.

I'm going to run the environment, following the steps you described, to be able to connect with the front-end.

I tell you if I need help, ok?

**Comment by felipewind** [comment]
Hello @lorenzowind !

Awesome!

I'm anxious to see the UI!

Just tell me if you need some help.

**Comment by felipewind** [comment]
Hi @lorenzowind  !

As I was studying Angular, I've create a front-end version with it and already did the integration.

Thanks!
