### ISSUE TITLE
Define the API contract for insert clients

### ISSUE THREAD

**Issue by felipewind** [felipewind/client-management#2]
Hello @lorenzowind!

Let's define the contract for the API to insert clients!

I thought in something very simple, to start, as:
```
String name;
String birthDate;
```

It would be with JSON format.

What do you think?

I can create the back-end project and you the front-end.

**Comment by lorenzowind** [comment]
Hi @felipewind.

Maybe we should add more fields, such as email, phone number, etc. Also considering some unique data of course, like the id of the client. And I agree to work with JSON format.

**Comment by lorenzowind** [comment]
I can take the front-end context.

Let's define the technologies we are going to use, could you create another issue for that?

**Comment by felipewind** [comment]
> Hi @felipewind.
> 
> Maybe we should add more fields, such as email, phone number, etc. Also considering some unique data of course, like the id of the client. And I agree to work with JSON format.

Good idea @lorenzowind !

What do you think about this layout:
- Request:
```json
{
   "name": "string",
   "birthDate": "string",
   "email": "string",
   "phoneNumber": 0
}
```
- Response ok - `200`:
```json
{
   "clientId": 0
}
```
- Validation problem - `422`:
```json
{
   "errorCode": 0
   "errorMessage": "string"
}
```

- System problem - `500`:
```json
{
   "errorCode": 0
   "errorMessage": "string"
}
```

**Comment by felipewind** [comment]
> define the technologies we are going to use

sure, I've opened https://github.com/felipewind/client-management/issues/4 for this.

**Comment by lorenzowind** [comment]
> What do you think about this layout:
> 
> * Request:
> 
> ```json
> {
>    "name": "string",
>    "birthDate": "string",
>    "email": "string",
>    "phoneNumber": 0
> }
> ```
> 
> * Response ok - `200`:
> 
> ```json
> {
>    "clientId": 0
> }
> ```
> 
> * Validation problem - `422`:
> 
> ```json
> {
>    "errorCode": 0
>    "errorMessage": "string"
> }
> ```
> 
> * System problem - `500`:
> 
> ```json
> {
>    "errorCode": 0
>    "errorMessage": "string"
> }
> ```
 
It looks good, but if you use a tool like swagger, will be clearer to follow the structure of all requests and responses of any service. Definitely will be helpful! Don't you agree?

**Comment by felipewind** [comment]
> > What do you think about this layout:
> > 
> > * Request:
> > 
> > ```json
> > {
> >    "name": "string",
> >    "birthDate": "string",
> >    "email": "string",
> >    "phoneNumber": 0
> > }
> > ```
> > 
> > 
> > 
> > * Response ok - `200`:
> > 
> > ```json
> > {
> >    "clientId": 0
> > }
> > ```
> > 
> > 
> > 
> > * Validation problem - `422`:
> > 
> > ```json
> > {
> >    "errorCode": 0
> >    "errorMessage": "string"
> > }
> > ```
> > 
> > 
> > 
> > * System problem - `500`:
> > 
> > ```json
> > {
> >    "errorCode": 0
> >    "errorMessage": "string"
> > }
> > ```
> 
> It looks good, but if you use a tool like swagger, will be clearer to follow the structure of all requests and responses of any service. Definitely will be helpful! Don't you agree?

Yes, you're right. Quarkus generate automatically one swagger definition using openapi spec.

I'll create the first verion of the back-end project and then I'll tell you how to access this swagger UI.

**Comment by felipewind** [comment]
Dude, I've just created a simple first verion of the back end, it's already in the `develop` branch. 

I know we should do code review, but this is just to get the swagger!

I didn't put anything on the README.md.

To run it and see the swagger, you can do this:

1. Clone our project locally;

2. Change to de develop branch;

3. Enter inside the "back-end" folder and type:
```bash
./mvnw compile quarkus:dev
```
4. Maven will download the dependencies to your local repository

5. You should see something like this:
![image](https://user-images.githubusercontent.com/47837222/97383415-5554e280-18ac-11eb-989b-a441011b498c.png)

6. Quarkus has an embedded server named Vert-x (I think);

7. Enter a browser and access our swagger:
http://localhost:8080/swagger-ui/

![image](https://user-images.githubusercontent.com/47837222/97383474-79b0bf00-18ac-11eb-8c22-ce16ee500ceb.png)


8. Click on Try it out on the POST client/insert

9. Now you can test three situations:

- If you write something like your name at the name, it will work and return a 200:
```json
{
  "birthDate": "string",
  "email": "string",
  "name": "lorenzo",
  "phoneNumber": 0
}
```
- If you let the name empty, it will return a 422:
```json
{
  "birthDate": "string",
  "email": "string",
  "name": "",
  "phoneNumber": 0
}
```

- If you put a wrong JSON, it will return a 500:
```json
{
  "phoneNumber": 0
}
```

10. If you access http://localhost:8080/openapi you will be able to download a schema of the api.

**Comment by lorenzowind** [comment]
That's great! I'm going to run and test it, and if I have a problem I tell you.

**Comment by felipewind** [comment]
Hello @lorenzowind !

I've created all the dummy endpoints for the /client CRUD:
- ![image](https://user-images.githubusercontent.com/47837222/97819577-3da0a400-1c88-11eb-9d60-66487ab4d0a1.png)

I've used the HTTP verbs to set the CRUD.

If you want to change anything please tell me.

**Comment by felipewind** [comment]
Dude, I've updated again the contract. I saw that the prototype you created for the front-end will need a list endpoint.

I'm not sure about the best strategy to define the response codes and the way you will pass the parameters.

![image](https://user-images.githubusercontent.com/47837222/97889258-e859a680-1d0a-11eb-8c3f-9fb57d83fd25.png)

**Comment by lorenzowind** [comment]
Hey @felipewind,

The client endpoints are good. But I didn't see them in detail yet, so I have some doubts.

1. How do you specify the client id for `get`, `put`, and `delete` operations? Did you put it in the query of the request?

2. Don't you think just one `get` request of the client is enough? Because all the client's data are present in the response of the `client/list`, so the `/client` won't be necessary.

About the code responses, I have followed the default code specifications in Wikipedia:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by felipewind** [comment]
> Hey @felipewind,
> 
> The client endpoints are good. But I didn't see them in detail yet, so I have some doubts.
> 
> 1. How do you specify the client id for `get`, `put`, and `delete` operations? Did you put it in the query of the request?
> 2. Don't you think just one `get` request of the client is enough? Because all the client's data are present in the response of the `client/list`, so the `/client` won't be necessary.
> 
> About the code responses, I have followed the default code specifications in Wikipedia:
> https://en.wikipedia.org/wiki/List_of_HTTP_status_codes


1. For the `DELETE` and `GET`, I put a query with the id. For the `PUT` , I defined a JSON with all client object. If you prefer, we can do different. 

2. I agree. I'll let only a `GET` listing all clients.

About the http responses, I've put like this:
- `200` - ok
- `422` - business error (Unprocessable Entity (WebDAV; RFC 4918)
The request was well-formed but was unable to be followed due to semantic errors)
- `500` - server error

I saw the website you quote, is it ok if I use only these 3 returns (200, 422 and 500) for this first moment?

**Comment by lorenzowind** [comment]
> 1. For the `DELETE` and `GET`, I put a query with the id. For the `PUT` , I defined a JSON with all client object. If you prefer, we can do different.
> 2. I agree. I'll let only a `GET` listing all clients.

Oh yeah, that's fine!

> About the http responses, I've put like this:
> 
> * `200` - ok
> * `422` - business error (Unprocessable Entity (WebDAV; RFC 4918)
>   The request was well-formed but was unable to be followed due to semantic errors)
> * `500` - server error
> 
> I saw the website you quote, is it ok if I use only these 3 returns (200, 422 and 500) for this first moment?

Yes for sure, while we are not working with authentication is not necessary to have more types of response codes.

**Comment by felipewind** [comment]
A friend borrowed me a server, the back is end is running there. 

The swagger documentation is available at:
- http://www.guiodai.com:8080/swagger-ui/

**Comment by felipewind** [comment]
As we agreed on this contract, I will close this issue.
