### ISSUE TITLE
Define the technologies for the back-end and the front-end

### ISSUE THREAD

**Issue by felipewind** [felipewind/client-management#4]
@lorenzowind 

What tecnhologies do you think we should use for the back-end and the front-end?

I would like to use Java/Quarkus with PostgreSQL in the back-end. Do you agree?

For the front-end, I don't know the better choice.

**Comment by lorenzowind** [comment]
Hi @felipewind, 

> I would like to use Java/Quarkus with PostgreSQL in the back-end. Do you agree?

I agree. Using docker-compose for containerizing the back-end too.

**Comment by lorenzowind** [comment]
Well, as responsible for the front-end, I'm thinking in utilize React.js to build the interfaces, also using the Typescript language for better maintenance. That's ok for you?

**Comment by felipewind** [comment]
Ok, I can use docker-compose for the back-end.

For me React.js would be awesome.

I'll close this issue, as this already defined, feel free to open it again if you want.
