### ISSUE TITLE
Define the gitflow for the project

### ISSUE THREAD

**Issue by felipewind** [felipewind/client-management#5]
@lorenzowind , and what about our gitflow for this project?

I thought about doing this way:
- Create a `develop` branch from our current `main` branch;
- Each of us create individual branches related to issues.
- We merge our branches on the `develop` branch until we have a first runnable version of this project;
- We finally merge our `develop` into the `main`.

I would also like to make squash merges to avoid to much log history in the git history.

What do you think? Please feel free to suggest what you prefer.

**Comment by lorenzowind** [comment]
Hey @felipewind,

> What do you think? Please feel free to suggest what you prefer.

That's perfect for me, I have worked on some projects that I followed the exact same flow.

**Comment by lorenzowind** [comment]
Do you have a strategy for the git commit messages?

Personally, I always try to follow this structure of Udacity recommendation: https://udacity.github.io/git-styleguide/

**Comment by felipewind** [comment]
> Do you have a strategy for the git commit messages?
> 
> Personally, I always try to follow this structure of Udacity recommendation: https://udacity.github.io/git-styleguide/

Looks very interesting. When this site talks about three parts of the commit, is it talking about the `git commit` messages?

Do I have to use a break line character like "\n" to split between type, body and footer?

Or this is commit message is for when we make the merge?

Can you explain better please?

![image](https://user-images.githubusercontent.com/47837222/97377356-98a85480-189e-11eb-98f0-bc715daf2dd7.png)

**Comment by lorenzowind** [comment]
> Do I have to use a break line character like "\n" to split between type, body and footer?

> Or this is commit message is for when we make the merge?
 
> Can you explain better please?

Well, this kind of commit message structure - defining the type, body, and footer - is more complete, but I think just following the type definition fits great, for example when you create a new feature, the commit could be something like:

`feat: name of the feature`

Or supposing you have organized the folder structure, will be like:

`chore: project folder structure`

I think using this strategy for anything in the project helps to commit more and describe exactly what was done, which facilitates the step-by-step way to develop, sounds cliche but don't you agree?

**Comment by felipewind** [comment]
> > Do I have to use a break line character like "\n" to split between type, body and footer?
> 
> > Or this is commit message is for when we make the merge?
> 
> > Can you explain better please?
> 
> Well, this kind of commit message structure - defining the type, body, and footer - is more complete, but I think just following the type definition fits great, for example when you create a new feature, the commit could be something like:
> 
> `feat: name of the feature`
> 
> Or supposing you have organized the folder structure, will be like:
> 
> `chore: project folder structure`
> 
> I think using this strategy for anything in the project helps to commit more and describe exactly what was done, which facilitates the step-by-step way to develop, sounds cliche but don't you agree?

I totally agree. I'll do this way in my commits.

And what about the pattern to branch names? develop we already agreed, and what about the others?

Should we create a CONTRIBUTING.md file with this guideline? So if someone enter in our project could see how to contribute.

Do you have access to merge directly into the repository?

For me, as we are working in different parts of the project, I guess we could merge directly into develop without code review, what do you think?

**Comment by lorenzowind** [comment]
> Should we create a CONTRIBUTING.md file with this guideline? So if someone enter in our project could see how to contribute.

It's a great idea, could you do this for us?
 
> Do you have access to merge directly into the repository?

Yes, I think so, I'm going to try to merge into the develop branch when I finish a simple version of the front-end.

> For me, as we are working in different parts of the project, I guess we could merge directly into develop without code review, what do you think?

I agree. It will definitely not be a problem.

**Comment by felipewind** [comment]
> > Should we create a CONTRIBUTING.md file with this guideline? So if someone enter in our project could see how to contribute.
> 
> It's a great idea, could you do this for us?
> 
> > Do you have access to merge directly into the repository?
> 
> Yes, I think so, I'm going to try to merge into the develop branch when I finish a simple version of the front-end.
> 
> > For me, as we are working in different parts of the project, I guess we could merge directly into develop without code review, what do you think?
> 
> I agree. It will definitely not be a problem.

I've created the `CONTRIBUTING.md` and the `CODE_OF_CONDUCT.md` and put them in the main branch.

If you agree with them, please close this issue.

Or, if you want to change anything just say here or change these files directly.

**Comment by lorenzowind** [comment]
> I've created the `CONTRIBUTING.md` and the `CODE_OF_CONDUCT.md` and put them in the main branch.

Thanks, @felipewind. The files look perfect for me.
