### ISSUE TITLE
Create first version of the front-end

### ISSUE THREAD

**Issue by lorenzowind** [felipewind/client-management#8]
Create the first version of the front-end project.

This version will have the React.js initialization structure with Typescript.

Also, it will have the first version of non-functional interfaces to manage clients.

**Comment by lorenzowind** [comment]
Hey @felipewind,

I created a medium-fidelity version of the client management's design, could you take a look and give feedback?

You just need to access this link and you will be able to visualize:
https://xd.adobe.com/view/96e36175-32c0-4c37-a166-d2575eb54e9b-c3b0/

**Comment by felipewind** [comment]
> Hey @felipewind,
> 
> I created a medium-fidelity version of the client management's design, could you take a look and give feedback?
> 
> You just need to access this link and you will be able to visualize:
> https://xd.adobe.com/view/96e36175-32c0-4c37-a166-d2575eb54e9b-c3b0/

Wow dude!

It's awesome! Congratulations!

I've updated the #2 . As soon as we agree on the api contract, I'll create the database and set everything to run with docker-compose.

**Comment by lorenzowind** [comment]
That's great! Let me know if you want to change something in the design,

**Comment by felipewind** [comment]
> That's great! Let me know if you want to change something in the design,

For me the design is very good.
